
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const LOGIN_SELLER_REQUEST = "LOGIN_SELLER_REQUEST";
export const LOGIN_SELLER_SUCCESS = "LOGIN_SELLER_SUCCESS";
export const LOGIN_SELLER_FAIL = "LOGIN_SELLER_FAIL";

export const REGISTER_SELLER_REQUEST = "REGISTER_SELLER_REQUEST";
export const REGISTER_SELLER_SUCCESS = "REGISTER_SELLER_SUCCESS";
export const REGISTER_SELLER_FAIL = "REGISTER_SELLER_FAIL";

export const LOAD_SELLER_REQUEST = "LOAD_SELLER_REQUEST";
export const LOAD_SELLER_SUCCESS = "LOAD_SELLER_SUCCESS";
export const LOAD_SELLER_FAIL = "LOAD_SELLER_FAIL";

export const LOGOUT_SELLER_SUCCESS = "LOGOUT_SELLER_SUCCESS";
export const LOGOUT_SELLER_FAIL = "LOGOUT_SELLER_FAIL";