export const OTP_SEND_REQUEST = "OTP_SEND_REQUEST";
export const OTP_SEND_SUCCESS = "OTP_SEND_SUCCESS";
export const OTP_SEND_FAIL = "OTP_SEND_FAIL";

export const OTP_BASED_LOGIN_SELLER_REQUEST = "OTP_BASED_LOGIN_SELLER_REQUEST";
export const OTP_BASED_LOGIN_SELLER_SUCCESS = "OTP_BASED_LOGIN_SELLER_SUCCESS";
export const OTP_BASED_LOGIN_SELLER_FAIL = "OTP_BASED_LOGIN_SELLER_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const ALL_SELLERS_REQUEST = "ALL_SELLERS_REQUEST";
export const ALL_SELLERS_SUCCESS = "ALL_SELLERS_SUCCESS";
export const ALL_SELLERS_FAIL = "ALL_SELLERS_FAIL";

export const SELLER_DETAILS_REQUEST = "SELLER_DETAILS_REQUEST";
export const SELLER_DETAILS_SUCCESS = "SELLER_DETAILS_SUCCESS";
export const SELLER_DETAILS_FAIL = "SELLER_DETAILS_FAIL";

export const UPDATE_SELLER_REQUEST = "UPDATE_SELLER_REQUEST";
export const UPDATE_SELLER_SUCCESS = "UPDATE_SELLER_SUCCESS";
export const UPDATE_SELLER_RESET = "UPDATE_SELLER_RESET";
export const UPDATE_SELLER_FAIL = "UPDATE_SELLER_FAIL";

export const LOGIN_SELLER_REQUEST = "LOGIN_SELLER_REQUEST";
export const LOGIN_SELLER_SUCCESS = "LOGIN_SELLER_SUCCESS";
export const LOGIN_SELLER_FAIL = "LOGIN_SELLER_FAIL";

export const REGISTER_SELLER_REQUEST = "REGISTER_SELLER_REQUEST";
export const REGISTER_SELLER_SUCCESS = "REGISTER_SELLER_SUCCESS";
export const REGISTER_SELLER_FAIL = "REGISTER_SELLER_FAIL";

export const LOGOUT_SELLER_SUCCESS = "LOGOUT_SELLER_SUCCESS";
export const LOGOUT_SELLER_FAIL = "LOGOUT_SELLER_FAIL";

export const LOAD_SELLER_REQUEST = "LOAD_SELLER_REQUEST";
export const LOAD_SELLER_SUCCESS = "LOAD_SELLER_SUCCESS";
export const LOAD_SELLER_FAIL = "LOAD_SELLER_FAIL";

export const DELETE_SELLER_REQUEST = "DELETE_SELLER_REQUEST";
export const DELETE_SELLER_SUCCESS = "DELETE_SELLER_SUCCESS";
export const DELETE_SELLER_RESET = "DELETE_SELLER_RESET";
export const DELETE_SELLER_FAIL = "DELETE_SELLER_FAIL";

export const REMOVE_SELLER_DETAILS = "REMOVE_SELLER_DETAILS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";