export const CREATE_STORE_SETUP_REQUEST = "CREATE_STORE_SETUP_REQUEST";
export const CREATE_STORE_SETUP_SUCCESS = "CREATE_STORE_SETUP_SUCCESS";
export const CREATE_STORE_SETUP_FAIL = "CREATE_STORE_SETUP_FAIL";
export const CREATE_STORE_SETUP_RESET = "CREATE_STORE_SETUP_RESET";

export const BANK_ACCOUNT_SETUP_REQUEST = "BANK_ACCOUNT_SETUP_REQUEST";
export const BANK_ACCOUNT_SETUP_SUCCESS = "BANK_ACCOUNT_SETUP_SUCCESS";
export const BANK_ACCOUNT_SETUP_FAIL = "BANK_ACCOUNT_SETUP_FAIL";
export const BANK_ACCOUNT_SETUP_RESET = "BANK_ACCOUNT_SETUP_RESET";

export const BUSINESS_INFORMATION_SETUP_REQUEST = "BUSINESS_INFORMATION_SETUP_REQUEST";
export const BUSINESS_INFORMATION_SETUP_SUCCESS = "BUSINESS_INFORMATION_SETUP_SUCCESS";
export const BUSINESS_INFORMATION_SETUP_FAIL = "BUSINESS_INFORMATION_SETUP_FAIL";
export const BUSINESS_INFORMATION_SETUP_RESET = "BUSINESS_INFORMATION_SETUP_RESET";

export const DOCUMENT_UPLOAD_SETUP_REQUEST = "DOCUMENT_UPLOAD_SETUP_REQUEST";
export const DOCUMENT_UPLOAD_SETUP_SUCCESS = "DOCUMENT_UPLOAD_SETUP_SUCCESS";
export const DOCUMENT_UPLOAD_SETUP_FAIL = "DOCUMENT_UPLOAD_SETUP_FAIL";
export const DOCUMENT_UPLOAD_SETUP_RESET = "DOCUMENT_UPLOAD_SETUP_RESET";

export const VERIFICATION_SETUP_REQUEST = "VERIFICATION_SETUP_REQUEST";
export const VERIFICATION_SETUP_SUCCESS = "VERIFICATION_SETUP_SUCCESS";
export const VERIFICATION_SETUP_FAIL = "VERIFICATION_SETUP_FAIL";
export const VERIFICATION_SETUP_RESET = "VERIFICATION_SETUP_RESET";

export const GET_STORE_REQUEST = "GET_STORE_REQUEST";
export const GET_STORE_SUCCESS = "GET_STORE_SUCCESS";
export const GET_STORE_FAIL = "GET_STORE_FAIL";
export const GET_STORE_RESET = "GET_STORE_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";










